version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:80
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    restart: always

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unsecure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
