apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-q
  labels:
    app: api-q
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-q
  template:
    metadata:
      labels:
        app: api-q
    spec:
      containers:
        - name: api-q
          image: #{API_TAG}#
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: 100m
          env:
            - name: ASPNETCORE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-q-credentials
                  key: ASPNETCORE_CONNECTION_STRING
            - name: ASPNETCORE_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: api-q-credentials
                  key: ASPNETCORE_ORIGINS
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-q
  labels:
    app: api-q
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: api-q
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-q
  namespace: quran
spec:
  routes:
    - kind: Rule
      match: Host(`kb-beta-api.openarabic.io`)
      services:
        - kind: Service
          name: api-q
          namespace: openarabic
          passHostHeader: true
          responseForwarding:
            flushInterval: 1ms
          port: 8080
