name: Build, Push and Deploy

env:
  REGISTRY_NAME: docker.io/therealedenmind
  CLUSTER_NAME: edenmind-k8s
  CLUSTER_RESOURCE_GROUP: edenmind-rg

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push API to Docker Hub
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./api/Dockerfile
          tags: therealedenmind/api-q:${{ github.sha }}
          context: ./api
          push: true

      - name: Build and Push Web to Docker Hub
        uses: docker/build-push-action@v2.0.0
        with:
          file: ./web/Dockerfile
          tags: therealedenmind/web-q:${{ github.sha }}
          context: ./web
          push: true

      - name: Set target k8s cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Create secret in k8s cluster
        uses: Azure/k8s-create-secret@v1.1
        with:
          secret-type: generic
          secret-name: api-credentials
          namespace: openarabic
          arguments: |
            --from-literal=ASPNETCORE_CONNECTION_STRING="${{ secrets.ASPNETCORE_CONNECTION_STRING }}"
            --from-literal=ASPNETCORE_ORIGINS=${{ secrets.ASPNETCORE_ORIGINS }}

      - name: Replace SHA tag for containers
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./k8s/*.yaml"]'
        env:
          API_TAG: therealedenmind/api-q:${{ github.sha }}
          FRONTEND_TAG: therealedenmind/web-q:${{ github.sha }}

      - name: Deploy API and Web to AKS
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: koranensbudskap
          manifests: |
            ./k8s/web.yaml
            ./k8s/api.yaml
